### ISSUE TITLE
String length prefix

### ISSUE THREAD

**Issue by hpx7** [Electroid/bytebuf#1]
Was looking for a js binary reader/writer and came across your project, it looks great!

A common pattern is writing the string byteLength just before the actual string data so that the decoder can figure out how to read the string without needing to pass it a length. To conserve space, ideally the length is written as a varint.

Would you be open to adding this functionality to your library?

**Comment by Electroid** [comment]
Hi there! Glad you like it :)

> A common pattern is writing the string byteLength just before the actual string data [...] ideally the length is written as a varint.

This possible with the library today! Try this out to write a UTF-8 encoded string with a VarInt length prefix:
```js
let buf = ByteBuf.from(...)
buf.writeVarString("Hello world")
buf.reset()
console.log(buf.readVarString()) // { value: "Hello world", byteLength: 11 }
```

**Comment by hpx7** [comment]
Ah that's perfect, thank you!
